export const FETCH_USER = "FETCH_USER";
export const FETCH_CLASSROOMS = "FETCH_CLASSROOMS";
export const FETCH_CLASSROOM = "FETCH_CLASSROOM";
export const UPDATE_CLASSROOM = "UPDATE_CLASSROOM";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";
export const FETCH_JOIN_REQUESTS = "FETCH_JOIN_REQUESTS";
export const ACCEPT_JOIN_REQUESTS = "ACCEPT_JOIN_REQUESTS";
export const DECLINE_JOIN_REQUESTS = "DECLINE_JOIN_REQUESTS";
export const FETCH_CLASSROOM_STUDENTS = "FETCH_CLASSROOM_STUDENTS";
export const REMOVE_CLASSROOM_STUDENT = "REMOVE_CLASSROOM_STUDENT";
export const FETCH_ASSIGNMENTS = "FETCH_ASSIGNMENTS";
export const FETCH_ASSIGNMENT = "FETCH_ASSIGNMENT";
export const UPDATE_ASSIGNMENT = "UPDATE_ASSIGNMENT";
export const DELETE_ASSIGNMENT = "DELETE_ASSIGNMENT";
export const FETCH_SUBMISSIONS = "FETCH_SUBMISSIONS";
export const UPDATE_SUBMISSION = "UPDATE_SUBMISSION";
export const FETCH_REFERENCE_MATERIALS = "FETCH_REFERENCE_MATERIALS";
export const FETCH_REFERENCE_MATERIAL = "FETCH_REFERENCE_MATERIAL";
export const UPDATE_REFERENCE_MATERIAL = "UPDATE_REFERENCE_MATERIAL";
export const DELETE_REFERENCE_MATERIAL = "DELETE_REFERENCE_MATERIAL";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const SIGN_OUT = "SIGN_OUT";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const LOAD_EVENTS = "LOAD_EVENTS";
